### PR TITLE
Added an entry for 'module-companion for a function' idiom

### PR DESCRIPTION
**Pull request by JohnScience**

### CODE REVIEW

**Comment by simonsan** [comment]
Hey @JohnScience,
Thanks for opening this PR, after a short discussion we need to state, that this is something where the viability and complexity needs to be discussed first with the community, and we are not able to merge or review as is.

We feel like it adds too much complexity to a codebase, and we are unsure if the benefits are worth it. Of course, these things are highly subjective.

However, this was an interesting read, so we highly encourage you to write a blog post about it. If you don't have a personal blog, or you want our help let us know, and we will help you find the best way to share this article with the community, e.g. by sharing it on reddit and "this week in Rust".

The maintainers of this repo will also help you by re-sharing the blog post on their social media.
Once again, thank you for your effort and sorry if we aren't merging this.

I will copy the written article to our repository discussions, so people can talk about it and share their opinions.

**Comment by simonsan** [comment]
Discussion can be found here: https://github.com/rust-unofficial/patterns/discussions/418

**Comment by MarcoIeni** [comment]
Hi, I'm the other maintainer. Me and simonsan took the decision to close the PR together. I just wanted to thank you personally for the effort and repeat what simonsan told you: we strongly encourage to write this pattern as a blog post so that we can share it with the community.

Do you have a blog?

**Comment by JohnScience** [comment]
Blog post on Medium: https://medium.com/@demenev.dmitriy1/rust-module-companion-for-a-standalone-function-e66b1e551c6c

**Comment by MarcoIeni** [comment]
Great, thanks!

You can also add it to this week in rust if you want: https://github.com/rust-lang/this-week-in-rust/tree/master/draft

**Pull request closed without merging**
