### PR TITLE
Add note on #[non_exhaustive] for enums

### PR DESCRIPTION
**Pull request by Darneas**

### CODE REVIEW

**Comment by simonsan** [comment]
Hey thank you for the contribution, we are currently working on this in #135, issue is filed under #132 maybe you and @rcoh could work together on updating the article ;-)

**Comment by MarcoIeni** [comment]
Exactly, closing this. If you want to join the discussion in the issue or the PR you are welcome! :)

**Comment by simonsan** [comment]
We could merge this as a statement as long as the new article is not online, what do you think?

**Review by MarcoIeni — APPROVED** [review]

**Comment by simonsan** [comment]
Thank you for the contrib! ;-)

**Comment by Darneas** [comment]
You're welcome. Tuning into the issue + PR you have mentioned.

Sorry for making this PR without checking existing work. I read the article and though I should file the PR before I forget, also because the change was rather simple. But revisiting the whole article for new state of Rust makes total sense!

**Pull request merged**
