### PR TITLE
Improve mem-replace example

### PR DESCRIPTION
**Pull request by diwic**
Submitting a PR as suggested by llogiq [here](https://www.reddit.com/r/rust/comments/56l2pk/an_underused_idiom_memreplace_to_avoid_clones/d8kksx6)

### CODE REVIEW

**Comment by lfairy** [comment]
:+1: from me. I'll accept once the merge conflicts are resolved.

**Comment by diwic** [comment]
Hmm, not sure how that became a merge conflict. I've rebased it on top of master, can you check again if it's mergeable now?

**Comment by lfairy** [comment]
I checked your commits and they look okay. Thanks!

(As for the conflict: I think that was #34.)

**Comment by CasualX** [comment]
Yes that was my PR, you uh kinda clobbered all over it: the `String::new()` instead of `"".to_string()` was lost.

**Comment by diwic** [comment]
@CasualX Sorry! I made a new pull request (PR #40) that changes it back to String::new() again.

**Pull request merged**
