### PR TITLE
Update to use RFC2795 formatting

### PR DESCRIPTION
**Pull request by ciphergoth**

### CODE REVIEW

**Comment by simonsan** [comment]
Good idea, just to understand, did you look through the others to fix it as well and there haven't been any or just came by this one? If so, would you be able to go through the others and fix them as well? 😬 Would be lovely! 😊

**Comment by ciphergoth** [comment]
I just came by this one. Since it's about the use of the format macro it seems especially relevant!

**Comment by ciphergoth** [comment]
I've pushed a new branch that fixes it everywhere it's trivial.

My editor insists on fixing some stray whitespace at the same time. It's a lot of work for me to fix that.

**Comment by simonsan** [comment]
> I've pushed a new branch that fixes it everywhere it's trivial.
> 
> My editor insists on fixing some stray whitespace at the same time. It's a lot of work for me to fix that.

Yeah, don't mind. We use dprint, a rust tool. You can just run dprint fmt in the root and be fine :-)

**Comment by simonsan** [comment]
Thanks a lot! 🚀

**Review by simonsan — APPROVED** [review]

**Pull request merged**
