### PR TITLE
Update coercion-arguments.md

### PR DESCRIPTION
**Pull request by alsotang**
wrong order

### CODE REVIEW

**Comment by pickfire** [comment]
I don't see why it is wrong. Previous is `&String` vs `&str` and then `&Vec<T>` vs `&[T]`.

**Comment by alsotang** [comment]
image

Or maybe the `Box` one is not align?

**Comment by MarcoIeni** [comment]
I think it's Box to be not aligned, yes

**Comment by alsotang** [comment]
closed by https://github.com/rust-unofficial/patterns/pull/286/files

**Pull request closed without merging**
